version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    reviewers:
      - "Kaleaon"

  # Enable version updates for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    reviewers:
      - "Kaleaon"
    groups:
      # Group Android dependencies
      android:
        patterns:
          - "androidx.*"
          - "com.android.*"
      # Group Kotlin dependencies
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
      # Group Compose dependencies
      compose:
        patterns:
          - "*compose*"
      # Group test dependencies
      test:
        patterns:
          - "*test*"
          - "*junit*"
          - "*mockito*"
          - "*robolectric*"
          - "*truth*"