name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # Use a consistent JDK version (AGP 8.x requires JDK 17)
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          # Important: do not enable 'cache: gradle' here when using the Gradle action below

      # Official Gradle action: handles wrapper, dependency and configuration caching safely
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      # Install only the SDK components you need. Avoid caching the SDK/NDK.
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      # Optional: if NDK is needed, add a specific version (don’t cache it)
      # - name: Install NDK
      #   run: sdkmanager "ndk;26.1.10909125"

      # One-time cache reset (uncomment only if you suspect corruption)
      # - name: Reset Gradle caches for this run
      #   run: |
      #     rm -rf ~/.gradle/caches ~/.gradle/kotlin ~/.gradle/daemon

      - name: Build
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Unit tests
        run: ./gradlew --no-daemon --stacktrace testDebugUnitTest

      # Static analysis
      - name: ktlint check
        run: ./gradlew --no-daemon --stacktrace ktlintCheck

      - name: detekt check
        run: ./gradlew --no-daemon --stacktrace detekt

      # Android lint
      - name: Android lint
        run: ./gradlew --no-daemon --stacktrace lint