name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Set ANDROID_HOME
        run: echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
      - name: Run Lint
        run: ./gradlew lintDebug

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Set ANDROID_HOME
        run: echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
